// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kdyllefjyaxaqlorkruw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkeWxsZWZqeWF4YXFsb3JrcnV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2MTM4ODIsImV4cCI6MjA2NzE4OTg4Mn0.iOlF8FHovtovkyJNpp6xNSR1gnXiO1CtaUPy6lNatXc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});